---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: run teamcity build
description: runs a team city build
inputs:
  serverurl:
    description: argocd server url
    required: true
  user:
    description: user to authenticate
    required: true
  credential:
    description: credential to use
    required: true 
  projectname:
    description: project job id
    required: true
  projectdescription:
    description: project description
    required: true
  applicationname:
    description: application name
    required: true
  repourl:
    description: repo url
    required: true
  targetrevision:
    description: repo version
    required: true
  repopath:
    description: path within the Git repository git only
    required: false
  destnamespace:
    description: destination namespace
    required: true
  chartname:
    description: chart name for helm only
    required: false
  deploytype:
    description: either git or helm
    required: true
  debug:
    required: false
    default: "false"
  poll_time:
    required: false
    default: "2"
  

runs:
  using: composite
  steps:
    - id: login
      name: login to argocd
      uses: docker://gururepservice/argocd:latest
      shell: sh
      run: |
        #!/bin/bash
        
        ARGOCD_SERVER="${{ inputs.serverurl }}" 
        USERNAME="${{ inputs.user }}"
        PASSWORD="${{ inputs.credential }}"
        CREATE_PROJECT="false"
        SOURCE_TYPE="git"
        PROJECT_NAME="${{ inputs.projectame }}"
        PROJECT_DESCRIPTION="This is an example ArgoCD project."
        APP_NAME="${{ inputs.applicationname }}"
        REPO_URL="${{ inputs.repourl }}"
        TARGET_REVISION="${{ inputs.targetrevision }}"
        DEST_NAMESPACE="${{ inputs.destnamespace }}"
        REPO_PATH="${{ inputs.repopath }}"
        HELM_CHART="${{ inputs.chartname }}"

        

        
